### ISSUE TITLE
Submitting /csv/ form with no values generates Value error (ValueError at /csv/  time data '' does not match format '%d-%m-%Y')

### ISSUE THREAD

**Issue by sadawson** [kenjitoyama/gleba#2] opened 2011-07-11 04:24 UTC
gleba.app.report.csv_views.generate_date_range doesn't correctly sanitize form data. It attempts to parse a blank string into a date which ends up generating a Value error.

<b>Steps to replicate:</b>
(1) Retrieve http://localhost:8000/csv/ with a browser
(2) Click submit leaving start and end date blank.

<b>Expected Result:</b>
 Prompt for value or redirect back

<b>Actual Result:</b>
  ValueError raised.

Traceback:

<pre>
Environment:

Request Method: POST
Request URL: http://localhost:8000/csv/

Django Version: 1.3
Python Version: 2.7.1
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.staticfiles',
 'glebaAdmin',
 'apps.admin',
 'apps.report',
 'apps.bundy',
 'apps.weigh']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)
File "/home/sadawson/Documents/programming/gleba/../gleba/apps/report/csv_views.py" in generate_csv_range
  114.             request.POST['endDate'], "%d-%m-%Y")
File "/usr/lib/python2.7/_strptime.py" in _strptime
  325.                          (data_string, format))

Exception Type: ValueError at /csv/
Exception Value: time data '' does not match format '%d-%m-%Y'
</pre>

**Comment by sadawson** [comment] 2011-07-11 04:40
There should also be some input sanitation done. Its not only Null values that will cause problems, any ill formed string would cause problems.

Possible Resolutions: 
1) Default value entered.
 and
2) JavaScript to have the user prompted to enter some values if blank or mal-formed.
  and
3) Server-side check for parsable values in the event the user is accessing the action with a browser with no JavaScript or JavaScript disabled. Perhaps using curl etc.

**Comment by kenjitoyama** [comment] 2011-07-11 07:18
I believe just returning a default range is better. We can indicate that in the CSV page so that the user knows that that's the default.

**Comment by kenjitoyama** [comment] 2011-07-20 08:56
Why is this issue still open? I couldn't reproduce it again.

**Comment by sadawson** [comment] 2011-07-20 14:36
Dates that fail to parse get automatically converted to mean a report between today and today - 31 days.

If a user makes a typo or incorrectly enters the date into the wrong format it will use the default.

So outwardly to the user they will think it has worked as expect until they open the file and it will have the wrong dates.

I think that blank should use the last month thats fine but I think using a try catch to detect it will cause problems for users who type in the date incorrectly.

Blank -> default  to 31 days
Unparsable date -> error message

**Comment by kenjitoyama** [comment] 2011-08-02 00:45
Hi there,

Apologies for taking so long to reply to this thread. I think the behavior you just mentioned (blank -> default, parsing error -> error message) is precisely what was added in the last commit of csv_views.py (commit 7cbbdf76eea0969d3b90acd7df26de494f42e2c6). Have a look at lines 109~131 of csv_views.py.
If that's not what you mean, then please write it down here. If it's all good, then we can close this issue.

**Comment by kenjitoyama** [comment] 2011-08-02 00:46
I didn't intend to close the issue right away, I clicked the wrong button! Sorry, anyway, just have a look and reopen if necessary. =)

**Closed as completed by kenjitoyama** 2011-08-02 00:45 UTC
